//! 符号数据：分组 + 拼音别名 + 中文名。人工整理，覆盖中文写作与代码注释里
//! 真正会用到的符号；生僻符号交给系统字符面板，不在这里堆量。

/// 一个符号条目：`(符号, 拼音/英文别名, 中文名)`。
pub type Item = (&'static str, &'static str, &'static str);
/// 一组符号：`(组名, 组别名, 条目)`。
///
/// 组别名用于整组召回（`ujiantou` 列出所有箭头）；条目别名用于精确检索。
pub type Group = (&'static str, &'static str, &'static [Item]);

pub const GROUPS: &[Group] = &[
    (
        "标点",
        "biaodian bd",
        &[
            ("…", "shenglue ellipsis", "省略号"),
            ("—", "poszhehao dash", "破折号"),
            ("～", "bolang wavy", "波浪号"),
            ("·", "jiange dot", "间隔号"),
            ("「", "zuoyinhao", "左引号"),
            ("」", "youyinhao", "右引号"),
            ("『", "zuoshuangyin", "左双引号"),
            ("』", "youshuangyin", "右双引号"),
            ("“", "zuoyin", "左双引号"),
            ("”", "youyin", "右双引号"),
            ("‘", "zuodanyin", "左单引号"),
            ("’", "youdanyin", "右单引号"),
            ("《", "shuminghao", "书名号"),
            ("》", "shuminghao", "书名号"),
            ("〈", "danshuming", "单书名号"),
            ("〉", "danshuming", "单书名号"),
            ("【", "fangkuohao", "方头括号"),
            ("】", "fangkuohao", "方头括号"),
            ("〔", "liukuohao", "六角括号"),
            ("〕", "liukuohao", "六角括号"),
            ("§", "zhangjie section", "章节号"),
            ("¶", "duanluo pilcrow", "段落号"),
            ("†", "jianhao dagger", "剑标"),
            ("‰", "qianfenhao permille", "千分号"),
            ("‱", "wanfenhao", "万分号"),
        ],
    ),
    (
        "数学",
        "shuxue math sx",
        &[
            ("±", "zhengfu plusminus", "正负号"),
            ("×", "chenghao times", "乘号"),
            ("÷", "chuhao divide", "除号"),
            ("≠", "budengyu neq", "不等于"),
            ("≈", "yueyu approx", "约等于"),
            ("≡", "hengdengyu", "恒等于"),
            ("≤", "xiaoyudengyu leq", "小于等于"),
            ("≥", "dayudengyu geq", "大于等于"),
            ("∞", "wuqiong infinity", "无穷"),
            ("√", "genhao sqrt", "根号"),
            ("∑", "qiuhe sigma sum", "求和"),
            ("∏", "lianchen product", "连乘"),
            ("∫", "jifen integral", "积分"),
            ("∂", "pianwei partial", "偏微分"),
            ("∵", "yinwei because", "因为"),
            ("∴", "suoyi therefore", "所以"),
            ("∈", "shuyu in", "属于"),
            ("∩", "jiaoji cap", "交集"),
            ("∪", "bingji cup", "并集"),
            ("⊂", "zizi subset", "子集"),
            ("∠", "jiao angle", "角"),
            ("⊥", "chuizhi perp", "垂直"),
            ("∥", "pingxing parallel", "平行"),
            ("°", "du degree", "度"),
            ("′", "fen prime", "分（角度）"),
            ("″", "miao", "秒（角度）"),
        ],
    ),
    (
        "货币",
        "huobi money hb",
        &[
            ("￥", "renminbi yuan rmb", "人民币"),
            ("$", "meiyuan dollar", "美元"),
            ("€", "ouyuan euro", "欧元"),
            ("£", "yingbang pound", "英镑"),
            ("¥", "riyuan yen", "日元"),
            ("₩", "hanyuan won", "韩元"),
            ("₽", "lubu ruble", "卢布"),
            ("₹", "lubi rupee", "卢比"),
            ("¢", "meifen cent", "美分"),
            ("₿", "bitebi bitcoin", "比特币"),
        ],
    ),
    (
        "序号",
        "xuhao xh number",
        &[
            ("①", "yi one", "带圈 1"),
            ("②", "er two", "带圈 2"),
            ("③", "san three", "带圈 3"),
            ("④", "si four", "带圈 4"),
            ("⑤", "wu five", "带圈 5"),
            ("⑥", "liu six", "带圈 6"),
            ("⑦", "qi seven", "带圈 7"),
            ("⑧", "ba eight", "带圈 8"),
            ("⑨", "jiu nine", "带圈 9"),
            ("⑩", "shi ten", "带圈 10"),
            ("㈠", "kuohaoyi", "括号一"),
            ("㈡", "kuohaoer", "括号二"),
            ("㈢", "kuohaosan", "括号三"),
            ("Ⅰ", "luomayi roman", "罗马一"),
            ("Ⅱ", "luomaer roman", "罗马二"),
            ("Ⅲ", "luomasan roman", "罗马三"),
            ("Ⅳ", "luomasi roman", "罗马四"),
            ("Ⅴ", "luomawu roman", "罗马五"),
            ("Ⅵ", "luomaliu roman", "罗马六"),
            ("Ⅶ", "luomaqi roman", "罗马七"),
            ("Ⅷ", "luomaba roman", "罗马八"),
            ("Ⅸ", "luomajiu roman", "罗马九"),
            ("Ⅹ", "luomashi roman", "罗马十"),
        ],
    ),
    (
        "箭头",
        "jiantou arrow jt",
        &[
            ("→", "youjiantou right", "右箭头"),
            ("←", "zuojiantou left", "左箭头"),
            ("↑", "shangjiantou up", "上箭头"),
            ("↓", "xiajiantou down", "下箭头"),
            ("↔", "zuoyou", "左右箭头"),
            ("↕", "shangxia", "上下箭头"),
            ("↖", "zuoshang", "左上箭头"),
            ("↗", "youshang", "右上箭头"),
            ("↘", "youxia", "右下箭头"),
            ("↙", "zuoxia", "左下箭头"),
            ("⇒", "shuangyou implies", "双线右箭头"),
            ("⇐", "shuangzuo", "双线左箭头"),
            ("⇔", "dengjia iff", "等价箭头"),
            ("⇧", "shift", "上档键"),
            ("⌘", "command cmd", "命令键"),
            ("⌥", "option alt", "选项键"),
            ("⌃", "control ctrl", "控制键"),
            ("⏎", "huiche enter", "回车键"),
        ],
    ),
    (
        "图形",
        "tuxing shape tx",
        &[
            ("★", "shixinxing star", "实心星"),
            ("☆", "kongxinxing", "空心星"),
            ("●", "shixinyuan", "实心圆"),
            ("○", "kongxinyuan", "空心圆"),
            ("◎", "shuangyuan", "双圆"),
            ("■", "shixinfang", "实心方"),
            ("□", "kongxinfang", "空心方"),
            ("◆", "shixinling", "实心菱形"),
            ("◇", "kongxinling", "空心菱形"),
            ("▲", "shixinsanjiao", "实心三角"),
            ("△", "kongxinsanjiao", "空心三角"),
            ("▼", "daosanjiao", "倒三角"),
            ("※", "canzhao", "参照号"),
            ("✓", "duihao check", "对号"),
            ("✗", "cuohao cross", "错号"),
            ("☑", "gouxuan", "勾选框"),
            ("☐", "kongkuang", "空选框"),
            ("♠", "heitao spade", "黑桃"),
            ("♥", "hongtao heart", "红桃"),
            ("♦", "fangkuai diamond", "方块"),
            ("♣", "meihua club", "梅花"),
            ("♪", "yinfu note", "音符"),
            ("☯", "taiji", "太极"),
            ("♂", "nan male", "男性"),
            ("♀", "nv female", "女性"),
        ],
    ),
    (
        "单位",
        "danwei unit dw",
        &[
            ("℃", "sheshidu celsius", "摄氏度"),
            ("℉", "huashidu fahrenheit", "华氏度"),
            ("㎡", "pingfangmi", "平方米"),
            ("㎥", "lifangmi", "立方米"),
            ("㎏", "qianke kg", "千克"),
            ("㎞", "qianmi km", "千米"),
            ("㎝", "limi cm", "厘米"),
            ("㎜", "haomi mm", "毫米"),
            ("Ω", "oumu ohm", "欧姆"),
            ("µ", "wei micro", "微"),
        ],
    ),
    (
        "希腊",
        "xila greek xl",
        &[
            ("α", "alpha", "阿尔法"),
            ("β", "beta", "贝塔"),
            ("γ", "gamma", "伽马"),
            ("δ", "delta", "德尔塔"),
            ("ε", "epsilon", "艾普西龙"),
            ("θ", "theta", "西塔"),
            ("λ", "lambda", "兰布达"),
            ("μ", "mu", "缪"),
            ("π", "pi yuanzhoulv", "圆周率"),
            ("ρ", "rho", "柔"),
            ("σ", "sigma", "西格玛"),
            ("τ", "tau", "陶"),
            ("φ", "phi", "斐"),
            ("ω", "omega", "欧米伽"),
            ("Δ", "dadelta", "大德尔塔"),
            ("Σ", "dasigma", "大西格玛"),
        ],
    ),
    (
        "常用",
        "changyong cy",
        &[
            ("©", "banquan copyright", "版权"),
            ("®", "zhuce registered", "注册商标"),
            ("™", "shangbiao trademark", "商标"),
            ("№", "bianhao numero", "编号"),
            ("℡", "dianhua tel", "电话"),
            ("☎", "dianhua phone", "电话"),
            ("✉", "youjian mail", "邮件"),
            ("★", "wuxing", "五角星"),
            ("☀", "taiyang sun", "太阳"),
            ("☁", "yun cloud", "云"),
            ("☂", "san umbrella", "伞"),
            ("♾", "wuxian", "无限"),
        ],
    ),
];
